
function loss_vector_NLLS = cost_function_NLLS_NN(...
    para_vector, ...
    X_matrix, Y_matrix, num_nodes_vector, ...
    choices_act_funcs_array, choice_loss_func_output)

%--------------------------------------------------------------------------

[W_matrices_array, b_vectors_array] = convert_para_vector_to_W_b_arrays...
    (para_vector, num_nodes_vector);

[~, loss_vector_NLLS] = cost_function_NN(X_matrix, Y_matrix, ...
    W_matrices_array, b_vectors_array, ...
    choices_act_funcs_array, choice_loss_func_output);

end % of a function
