
function [grad_cost_W_matrices_array, grad_cost_b_vectors_array] = ...
    gradient_loss_function_NN(X_vector, Y_vector, ...
    W_matrices_array, b_vectors_array, ...
    choices_act_funcs_array, choice_loss_func_output)

%--------------------------------------------------------------------------

[a_L_X_vector, z_vectors_array, a_vectors_array]...
    = forward_pass_within_NN(X_vector, W_matrices_array, b_vectors_array,...
    choices_act_funcs_array);

[grad_cost_W_matrices_array, grad_cost_b_vectors_array] = ...
    backpropagation_within_NN(a_L_X_vector, Y_vector, ...,
    W_matrices_array, z_vectors_array, a_vectors_array, ...
    choices_act_funcs_array, choice_loss_func_output);

end
